name: OptiSMP
main: Nick3306.github.io.OptiSMP.Main
version: .01
commands:
   pfield:
      description: OptiSMP
      usage:
      permission: 
      permission-message: You do not have permission to use this command!